# Cakes

Cakes are fabulous. Check out the pineapple one - my favourite.

## Dark Aniseed Cake
Dan Lepard

* 350ml boiling water
* 175g pitted prunes
* 225g black treacle
* 75g dark ale
* 175g unsalted butter
* 175g dark muscovado sugar
* 450g spelt flour
* 4 tsp baking powder
* 4 tsp aniseed (or fennel) seeds
* 250g icing sugar
* 3 tbsp orange juice
* Zest of 1 orange

Preheat the oven to 180°C. Line the base of a 20cm square tin with nonstick paper.
Pour the boiling water over the prunes, leave to soak for five minutes, then purée in a blender with the treacle and ale.
In a warm bowl, beat the butter and sugar until fluffy and pale, stopping the mixer from time to time to scrape down the sides and break up any hefty sugar lumps.
Slowly beat in the prune mixture until combined into a dark creamy liquid. Sieve the spelt to remove lumps, but add back any bran bits that get caught in the mesh.
Toss the baking powder and seeds through the flour, then beat evenly through the prune mixture.
Tip the mixture into the tin, smooth the top and bake for 50 minutes, until a skewer inserted into the middle comes out clean.
Cool in the tin, then transfer to a plate. Beat the icing sugar and orangey bits together, then spread this over the cake.

## Easy carrot cake
Dan Lepard

* 175g plain flour
* 2 tsp baking powder
* 1 tsp ground cinnamon
* 1/2 tsp ground cloves and nutmeg
* 200g light brown sugar
* 150ml sunflower oil
* 2 large eggs
* 150-200g grated carrot
* 75g chopped walnuts/pecans

For the icing

* 200g soft cream cheese
* 100g creme fraiche
* 125g icing sugar
* 1 lemon (zest and 2 tsp juice)

Preheat oven to 180°C and line two 20cm round sponge tins
Mix flour, baking powder and spices in one bowl. 
In another bowl, mix sugar with oil and with with eggs until smooth.
Stir in carrots and walnuts. Fold in the sifted dry ingredients.

Divide and cake between two tins and bake for 25 min. 
Cool in tin. 


## Date and walnut loaf 
Jill Dupleix (Favourite Food)

* 130g chopped dates
* 30g brown sugar
* 50g chopped walnuts
* 1 small banana
* 15g butter
* 1tsp bicarbonate of soda
* 225ml boiling water
* 200g self-raising flour

Pour boiling water over dates, sugar, walnuts, banana and butter. Add bicarb. Stir and let cool. Mix in the flour. Sprinkle with demarara sugar. Cook for 30-40 min at 180°C. Makes 1lb loaf tin.

## Chocolate Guinness Cake
Nigella Lawson

For the Cake

* 250 millilitres guinness
* 250 grams unsalted butter
* 75 grams cocoa powder
* 400 grams caster sugar
* 142 ml sour cream
* 2 large eggs
* 1 tablespoon vanilla extract
* 275 grams plain flour
* 2½ teaspoons bicarbonate of soda

For the Topping

* 300 grams cream cheese
* 150 grams icing sugar
* 125 millilitres double cream (or whipping cream)

Preheat the oven to gas mark 4/180°C/350ºF, and butter and line a 23cm / 9 inch springform tin.
Pour the Guinness into a large wide saucepan, add the butter - in spoons or slices - and heat until the butter's melted, at which time you should whisk in the cocoa and sugar. Beat the sour cream with the eggs and vanilla and then pour into the brown, buttery, beery pan and finally whisk in the flour and bicarb.
Pour the cake batter into the greased and lined tin and bake for 45 minutes to an hour. Leave to cool completely in the tin on a cooling rack, as it is quite a damp cake.

When the cake's cold, sit it on a flat platter or cake stand and get on with the icing. Lightly whip the cream cheese until smooth, sieve over the icing sugar and then beat them both together. Or do this in a processor, putting the unsieved icing sugar in first and blitz to remove lumps before adding the cheese.
Add the cream and beat again until it makes a spreadable consistency. Ice the top of the black cake so that it resembles the frothy top of the famous pint.

## Blueberry Almond Slices
Dan Lepard

* 150g fresh blueberries
* 2 tsp cornflour
* 125g caster sugar
* 150g plain flour
* ½ tsp baking powder
* 50g ground almonds
* 100g unsalted butter, plus 1 tsp extra
* 1 large egg, beaten
* 50ml milk
* 2 tsp honey
* 100g light brown sugar
* 100g flaked almonds

Heat 100ml water with the blueberries, cornflour and 50g caster sugar in a pan; stir gently until the blueberries bleed and the mixture thickens. Measure the flour, baking powder, ground almonds and 75g caster sugar into a bowl, rub in 100g butter, then work through the beaten egg. Butter a square 20cm tin and pat the mixture into the base of it.

To make the almond crust, simmer the milk, honey, brown sugar and almonds until slightly thickened.

Spread blueberry compote over the top of the cake mix, top this with the almond mixture, and bake at 180C (160C fan-assisted)/350F/ gas mark 4 for about 35 minutes. Remove and leave to cool before cutting into slices.

## Dan lepard pineapple

##  Blueberry Tart with Rye
Nordic Bakery

For the pastry
- 100g (3.5 oz) Unsalted butter, softened at room temperature
- 85g (3 oz) Caster sugar
- 1 Egg, lightly beaten
- 100g (3.5 oz) Plain flour
- 60g (2.1 oz) Wholemeal rye flour
- 1 tsp Baking powder

For the filling
- 100g (3.5 oz) Crème fraîche
- 150ml (5.3 fl oz) Soured cream
- 1 Egg, lightly beaten
- 40g (1.4 oz) Caster Sugar
- 1 tsp Vanilla extract
- 250g (8.8 oz) Blueberries

Equipment
- 1 x 24cm loose-bottomed, fluted tart tin,greased

Preheat the oven to 200°C (400°F) Gas 6.
Put the butter and sugar in a mixing bowl and beat until well mixed. Gradually add the egg, mixing well. Tip in the flours and baking powder and mix again until a dough has formed. Transfer the dough to the tart tin and push and press it into the tin until the base and sides are evenly covered with a neat layer of dough.
To make the filling, put the crème fraîche, soured cream, egg, sugar and vanilla extract in a mixing bowl and mix well. Pour into the pastry case, then scatter the blueberries into the tart. Bake in the preheated oven for 25 minutes, or until the filling has set and the pastry is golden brown.

## Chocolate Cheesecake

* 150 g digestive biscuits, crushed
* 45 g butter, melted
* 110 g caster sugar
* 120 ml whipping cream
* 150 g dark chocolate, melted and cooled
* 2 tbsp cocoa powder
* 200 g cream cheese

Mix the biscuits with the butter and 1 tablespoon of the sugar. Press into a 18cm springform cake tin and refrigerate. 

Whip the cream until soft peaks form. Add the cooled melted chocolate, then the cocoa powder mix. Blend well and set aside. 

Beat the cream cheese and remaining sugar together. Fold into the cream chocolate mixture and mix thoroughly to ensure all of the ingredients are fully incorporated. 

Spread the mixture on top of the crushed biscuits. Refrigerate for at least an hour to set, then serve.

##  Welsh cakes

* 225g self-raising flour, sieved
* 100g salted butter
* 1 egg
* handful of sultanas
* milk, if needed
* 40g caster sugar
* 1/2 tsp mixed spice.

Rub the fat into the sieved flour to make breadcrumbs. Add the sugar, dried fruit and then the egg. Mix to combine, then form a ball of dough, using a splash of milk if needed.
Roll out the pastry until it is a 5mm/¼in thick and cut into rounds with a 7.5-10cm/3-4in fluted cutter.
You now need a bakestone or a heavy iron griddle. Rub it with butter and wipe the excess away. Put it on to a direct heat and wait until it heats up, place the Welsh cakes on the griddle, turning once. They need about 2-3 minutes each side. Each side needs to be caramel brown before turning although some people I know like them almost burnt.
Remove from the pan and dust with caster sugar while still warm. Some people leave out the dried fruit, and split them when cool and sandwich them together with jam.

