# Curry `r emo::ji("curry")` {-}

## Black-eyed beans with mushrooms {-}
Madhur Jaffrey

* 250g dried black-eyed beans 
* 250g mushrooms
* 1tsp cumin seeds
* 1 cinnamon stick
* 1 large onion
* 3 cloves garlic
* 400g tinned tomatoes
* 2 tsp ground corriander
* 1 tsp ground cumin
* 1/2 tsp turmeric
* 1/4 tsp chilli powder
* 3 tbsp fresh corriander

Cook beans in 750ml of water. 
Fry cumin seeds and cinammon stick in hot oil.Add in garlic and onion. Then mushrooms and cook until wilted.
Add tomatoes and spice. Cook for 10 mins. Throw in beans and cook for 20 min. 

##  The Perfect Dahl {-}

* 200-400g Dahl ( + red lentils?)
* Throw in garlic and turmeric
* Flash fry cumin seeds and mustard seeds
* Onion garlic add
* Sweet potato/ spinach?


## Spiced Butternut Squash {-}
Sophie Grigson (Eat your greens)

* 600g butternut squash
* ¼ tsp turmeric
* 1 bay leaf
* ½ star anise
* 150ml water
* 1 small onion
* 1 clove garlic
* 50g butter
* 1 tsp cumin seeds
* 1 tsp coriander seeds
* 1 inch ginger

Squash, turmeric, bay leaf & star anise and water in pan. Lid on 20 min. Mash.
Cook rest separately. Add to squash. Serve with rice.