# Mexican `r emo::ji("burrito")` {-}

## Mexican Bean Chilli {-}

* 150g kidney beans ( or 1 tin)
* 150g black eyed beans ( 1 tin)
* 1 large carrot
* 1 stick celery
* 1 onion
* 1 clove
* 1 red chilli
* 1 tbsp tomato puree
* 1 tsp ground cumin
* 1 tsp ground coriander
* 1 bay leaf
* 1 cinnamon stick
* 1 tsp smoked paprika
* 1 tsp soy sauce
* 1 tin of tomatoes
* 1 pepper (frozen?)
* Fresh coriander


Soak beans
Fry carrot, celery, onion, garlic, chilli in oil.
Add tom puree, cumin, coriander, bay, cinnamon, paprika.
Add chopped toms, peppr and soy. Simmer and cook on low for 20min.
Add beans, simmer, cook for 15min. 

Serve with rice and sour cream.

## Refried beans {-}

* 1 onion
* 1-3 cloves garlic
* 2 tins beans pinto or kidney (250g dried)
* 1 tsp cumin powder
* 1/4 tsp corriander powder
* 150ml stock
* 2 tbsp fresh corriander 

Fry onion garlic in oil
Add spices, beans, stock. 
Cook until soft (10-20 min) and mash. 

##  Moroccan Spiced Chickpeas with Spinach {-}

- 1 onion
- 2 cloves garlic
- 2-3 tsp Moroccan spice mix(2 tbsp cumin and corriander, 1 tbsp tumeric, 1-2 tbsp chilli powder )
- 200g toms
- 400g chickpeas
- handful fresh spinach
- yogurt (to serve)

Cook onion in oil (5min).
Stir garlic and spice mix, fry for a few seconds then tip in toms and mash them.
Bring to boil, add chickpeas, cover and simmer for 8min.
Chuck in spinach and coriander and cook for 2 min.
Serve with naan and yogurt.


##  Rice and peas {-}

* 1 onion
* 2 cloves of garlic
* thyme 
* 50g creamed coconut
* 200g rice
* 450ml stock
* 1 chilli
* 200g cooked kidney beans
* all spice berry

Fry onion and garlic. Add everything else. bring to boil, cover and cook for 20 min. 
