# Bread `r emo::ji("baguette_bread")` {-}

## Bread Machine Loaf - Sandwich Setting {-}

* 1 tsp yeast
* 500g wholemeal bread flour
* 3/4 tsp salt
* 350ml water

## Toasted Teacakes {-}

Makes 12

* 225ml warm milk
* 2 tsp yeast
* 50g light muscovado sugar
* 450g strong white bread flour
* 1 tsp ground mixed spice
* 50g butter cubed
* 1 egg, beaten
* 150g mixed currants/sultanas
* 25g candied peel

Pour milk in jug, stir in yeast and 1 tsp sugar. Stand for 15-20 min until frothy.
Flour, spice in bowl. Rub in the butter.
Stir in sugar, egg, yeast and mix with round blended knife. Add milk if dough is dry.
Tip onto floured surface, knead for 10 min until smooth, working in currants etc. half way.
Put dough in clean lightly greased bowl and cover with clingfilm, leave to r ise in warm place for 1.5 - 2 hours until doubled in size.
Grease large baking sheet.
Divide dough into 12 even pieces, shape in ball then flatten.
Cover loosely with greased clingfilm and leave rise for 30 min.
Preheat to 200*C
Glaze with egg and bake for 15min.

##  Pitta Bread {-}
Paul Hollywood

* 250g strong white flour, plus extra for dusting
* 7g instant yeast
* 20g nigella seeds or black onion seeds
* 1 tsp salt
* 160mlwater
* 2 tsp olive oil, plus extra for kneading

In a bowl, mix together the flour, yeast, nigella seeds and salt. Add 120ml/4fl oz of the water and 1½ teaspoons of oil. Using your fingers mix the ingredients together. Gradually add the remaining water and oil until all the flour has come away from the sides and you have a soft dough. (You may not need all the water; the dough should be soft and not sticky.)
Pour a little oil onto your work top. Place the dough on top and knead for 5-10 minutes. The dough will be wet in the beginning but will form a smooth dough once kneaded. Once a smooth dough is achieved, place it into a clean, oiled bowl. Cover and leave to prove until doubled in size.
Preheat the oven to 250C/475F/Gas 9 and place a clean baking tray or baking stone on the middle shelf.

When the dough has doubled in size, tip it out onto a work surface dusted with flour. Knock the dough back by folding it inwards over and over again until all the air is knocked out. Split the dough into 4-6 equally sized balls. Roll each ball into an oval shape 3-5mm thick.
Remove the hot tray from the oven, dust with flour and place the pitta breads on it. You may have to cook them in batches.
Bake for 5-10 minutes, or until they just start to colour. Remove them from the oven and cover with a clean cloth until they are cool.

## Tortillas {-}
Linda Collister

* 225g flour
* 25g wholemeal flour
* 1/2 tsp salt
* 2 pinches ground cumin
* 1 tsp baking powder
* 40g butter
* 150ml warm water

Mix flour, salt, spices and baking powder in a bowl. Rub in butter to make crumbs. Gradually work in the flour to make a soft but not sticky dough. Cover the bowl with clingfilm and let rest for 30 min. 

Divide the dough into 8 equal pieces and shape into balls. Roll out on a floured surface to make disks 8 inches across. 

Heat in a griddle 1 min per side. 

## Nordic Cinnamon Buns {-}

Makes 12-13

For the dough

* lukewarm milk 570ml
* caster sugar 150g
* fresh yeast 45g (or easy-blend dried yeast, according to manufacturer's instructions)
* cardamom seeds 1 tsp, crushed with a pestle and mortar
* unsalted butter 180g, melted
* egg 1
* plain flour 1 kg

For the filling

* unsalted butter 100g, softened at room temperature
* dark brown soft sugar 200g
* ground cinnamon 3 tbsp

For the glaze
* caster sugar 85g
* freshly squeezed lemon juice 1 tbsp

To make the dough, put the milk, sugar, yeast, cardamom, melted butter and egg in a food processor or mixer with a dough hook. With the motor running, gradually add the flour until it is all incorporated and the dough has come together. Transfer the dough to a bowl, cover with a clean tea towel and leave to prove in a warm place for 1 hour, or until it has doubled in size.
After an hour, punch down the dough and transfer to a lightly floured surface. Using a rolling pin, roll it out until it is about 30cm x 80cm and 7mm thick.

For the filling, spread the butter evenly over the dough and sprinkle the sugar and cinnamon all over the top.
Roll the dough up from a long side. Cut into roughly 6cm rolls, but cut them at an angle – so, make the first cut diagonally, then the second cut about 6cm along diagonally in the opposite direction. You should get a roll that looks like a trapezium (or a triangle with the tip chopped off). Carefully transfer the buns to the prepared baking trays, with the longest edge of the bun sitting on the tray, cover with tea towels again and leave to prove in a warm place for 30-60 minutes, until almost doubled in size.

Preheat the oven to 200C/gas mark 6. Bake the buns in the preheated oven for 20-25 minutes, or until golden brown.
To make the glaze, put the sugar, lemon juice and 100ml water in a small pan and bring to the boil. Simmer for 10-15 minutes, until slightly thickened. The glaze will be quite watery.
Remove the buns from the oven, transfer to a wire rack and brush the glaze generously over them. Leave them to cool before serving.
