# Main meals

## Black-eyed beans with mushrooms
Madhur Jaffrey

* 250g dried black-eyed beans 
* 250g mushrooms
* 1tsp cumin seeds
* 1 cinnamon stick
* 1 large onion
* 3 cloves garlic
* 400g tinned tomatoes
* 2 tsp ground corriander
* 1 tsp ground cumin
* 1/2 tsp turmeric
* 1/4 tsp chilli powder
* 3 tbsp fresh corriander

Cook beans in 750ml of water. 
Fry cumin seeds and cinammon stick in hot oil.Add in garlic and onion. Then mushrooms and cook until wilted.
Add tomatoes and spice. Cook for 10 mins. Throw in beans and cook for 20 min. 

## Mexican Bean Chilli

* 150g kidney beans ( or 1 tin)
* 150g black eyed beans ( 1 tin)
* 1 large carrot
* 1 stick celery
* 1 onion
* 1 clove
* 1 red chilli
* 1 tbsp tomato puree
* 1 tsp ground cumin
* 1 tsp ground coriander
* 1 bay leaf
* 1 cinnamon stick
* 1 tsp smoked paprika
* 1 tsp soy sauce
* 1 tin of tomatoes
* 1 pepper (frozen?)
* Fresh coriander


Soak beans
Fry carrot, celery, onion, garlic, chilli in oil.
Add tom puree, cumin, coriander, bay, cinnamon, paprika.
Add chopped toms, peppr and soy. Simmer and cook on low for 20min.
Add beans, simmer, cook for 15min. 

Serve with rice and sour cream.


##  Moroccan Spiced Chickpeas with Spinach

- 1 onion
- 2 cloves garlic
- 2-3 tsp Moroccan spice mix(2 tbsp cumin and corriander, 1 tbsp tumeric, 1-2 tbsp chilli powder )
- 200g toms
- 400g chickpeas
- handful fresh spinach
- yogurt (to serve)

Cook onion in oil (5min).
Stir garlic and spice mix, fry for a few seconds then tip in toms and mash them.
Bring to boil, add chickpeas, cover and simmer for 8min.
Chuck in spinach and coriander and cook for 2 min.
Serve with naan and yogurt.


##  The Perfect Dahl

* 200-400g Dahl ( + red lentils?)
* Throw in garlic and turmeric
* Flash fry cumin seeds and mustard seeds
* Onion garlic add
* Sweet potato/ spinach?

## Refried beans

* 1 onion
* 1-3 cloves garlic
* 2 tins beans pinto or kidney (250g dried)
* 1 tsp cumin powder
* 1/4 tsp corriander powder
* 150ml stock
* 2 tbsp fresh corriander 

Fry onion garlic in oil
Add spices, beans, stock. 
Cook until soft (10-20 min) and mash. 

##  Rice and peas

* 1 onion
* 2 cloves of garlic
* thyme 
* 50g creamed coconut
* 200g rice
* 450ml stock
* 1 chilli
* 200g cooked kidney beans
* all spice berry

Fry onion and garlic. Add everything else. bring to boil, cover and cook for 20 min. 

## Spiced Butternut Squash

* 600g butternut squash
* 1/4 tsp turmeric
* 1 bay leaf
* 150ml water
* 1 small onion
* 1 clove garlic
* 50g butter
* 1 tsp cumin seeds
* 1 tsp coriander seeds
* 1 inch ginger

Squash, turmeric, bay leaf and water in pan. Lid on 20 min. Mash.
Cook rest separately. Add to squash.
Serve with rice.

## Vegetarian Cheese Burgers

* 400g Red kidney beans rinsed and drained
* 1 small onion chopped finely
* 100g cheddar cheese
* 100g breadcrumbs
* 1 eggs
* plain flour (for dusting)
* 1 tbsp oil

Blitz beans, onion, cheese, breadcrumbs and egg in food blender. Flour hands, shape into burgers and fry.
