# Tray bakes `r emo::ji("chestnut")` {-}

## Fruit oat and seeds bar {-}

* 70g light muscovado
* 2 tbsp golden syrup
* 70g butter
* 250g oats
* 85g walnut pieces
* 50g seeds
* 25g cranberries
* 50g apricot
* 85g sultanas/raisins

Preheat oven to 160*C. Heat sugar, butter and golden syrup in a pan. When melted, stir in the other ingredients.

Press into a lined 23cmx23cm tin. Roll a tin can over the top (with baking paper) to pack down.

## Blueberry Almond Slices {-}
Dan Lepard

* 150g fresh blueberries
* 2 tsp cornflour
* 125g caster sugar
* 150g plain flour
* ½ tsp baking powder
* 50g ground almonds
* 100g unsalted butter, plus 1 tsp extra
* 1 large egg, beaten
* 50ml milk
* 2 tsp honey
* 100g light brown sugar
* 100g flaked almonds

Heat 100ml water with the blueberries, cornflour and 50g caster sugar in a pan; stir gently until the blueberries bleed and the mixture thickens. Measure the flour, baking powder, ground almonds and 75g caster sugar into a bowl, rub in 100g butter, then work through the beaten egg. Butter a square 20cm tin and pat the mixture into the base of it.

To make the almond crust, simmer the milk, honey, brown sugar and almonds until slightly thickened.

Spread blueberry compote over the top of the cake mix, top this with the almond mixture, and bake at 180C (160C fan-assisted)/350F/ gas mark 4 for about 35 minutes. Remove and leave to cool before cutting into slices.

